[package]
name = "nodestor-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "nodestor"
path = "src/main.rs"

[[bin]]
name = "bench_apex"
path = "src/bin/bench_apex.rs"

[[bin]]
name = "bench_full_apex"
path = "src/bin/bench_full_apex.rs"

[[bin]]
name = "bench_apex_v2"
path = "src/bin/bench_apex_v2.rs"

[dependencies]
nodestor-core = { path = "../crates/nodestor-core" }
nodestor-scanner = { path = "../crates/nodestor-scanner" }
nodestor-formats = { path = "../crates/nodestor-formats" }
nodestor-transport = { path = "../crates/nodestor-transport" }
clap = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
reqwest = { version = "0.12", features = ["json", "stream"] }
dialoguer = "0.11"
tokio = { workspace = true, features = ["full"] }
tokio-stream = "0.1"
futures = "0.3"
urlencoding = "2.1"
nodestor-inference = { path = "../crates/nodestor-inference" }
nodestor-vulkan = { path = "../crates/nodestor-vulkan" }
nodestor-streaming = { path = "../crates/nodestor-streaming" }
walkdir = "2"
zstd = { workspace = true }
nodestor-gdeflate = { version = "0.1.0", path = "../crates/nodestor-gdeflate" }
nodestor-davi = { path = "../crates/nodestor-davi" }
indicatif = "0.18.4"
