[package]
name = "nodestor-scanner"
version.workspace = true
edition.workspace = true

[dependencies]
nodestor-core = { path = "../nodestor-core" }
nodestor-vulkan = { path = "../nodestor-vulkan" }
thiserror = { workspace = true }
serde = { workspace = true }
sysinfo = { workspace = true }
tracing = { workspace = true }


